// Generated by LiveScript 1.5.0
(function(){
  var blockstarter, contributors;
  blockstarter = require('../blockstarter.js');
  contributors = blockstarter.contributors;
  describe('Admin', function(_){
    var storage;
    storage = {
      apiKey: 'TEST-APIKEY'
    };
    it('contributors', function(done){
      var project;
      if (storage.apiKey == null) {
        throw "API Key is required";
      }
      project = 'KickCity';
      contributors({
        apiKey: storage.apiKey,
        project: project
      }, function(err, list){
        if (err != null) {
          throw err;
        }
        done();
      });
    });
  });
}).call(this);
