// Generated by LiveScript 1.5.0
(function(){
  var blockstarter, auth, panel, helpMe, address;
  blockstarter = require('../blockstarter.js');
  auth = blockstarter.auth, panel = blockstarter.panel, helpMe = blockstarter.helpMe, address = blockstarter.address;
  describe('Basic', function(_){
    var storage;
    storage = {
      sessionId: null,
      apiKey: 'TEST-APIKEY'
    };
    it('auth', function(done){
      var email, password, project, reference;
      if (storage.apiKey == null) {
        throw "API Key is required";
      }
      email = 'test@test.com';
      password = 'unique password';
      project = 'KickCity';
      reference = 'traffic-source';
      auth({
        email: email,
        password: password,
        project: project,
        reference: reference,
        apiKey: storage.apiKey
      }, function(err, session){
        if (err != null) {
          throw err;
        }
        if (session.sessionId == null) {
          throw "Session ID is missing";
        }
        storage.sessionId = session.sessionId;
        done();
      });
    });
    it('get-dashboard', function(done){
      if (storage.sessionId == null) {
        throw "Session is required";
      }
      if (storage.apiKey == null) {
        throw "API Key is required";
      }
      panel(storage, function(err, dashboard){
        if (err != null) {
          throw err;
        }
        storage.dashboard = dashboard;
        done();
      });
    });
    it('address', function(done){
      var type;
      this.timeout(5000);
      if (storage.sessionId == null) {
        throw "Session is required";
      }
      if (storage.apiKey == null) {
        throw "API Key is required";
      }
      if (storage.dashboard == null) {
        throw "Dashboard is required";
      }
      type = 'ltc';
      done();
    });
    it('help-me', function(done){
      if (storage.sessionId == null) {
        throw "Session is required";
      }
      if (storage.apiKey == null) {
        throw "API Key is required";
      }
      helpMe(storage, function(err, info){
        if (err != null) {
          throw err;
        }
        done();
      });
    });
  });
}).call(this);
